NAME: 'upsideagency'
SECRET_KEY_BASE: '033b3389f1706c1eb8d2de134c859e0af948a14b2be2c3ce75aaa8b7c31419b95cd4baa4cf84a27ade5bd2365592f875776099ac8798f3c8'
RAILS_MAX_THREADS: '2'
development:
  POSTGRES_USERNAME: 'eurovelo'
  POSTGRES_PASSWORD: 'eurovelo'
  HOST: 'HOST'
  FRONTEND: 'FRONTEND'
  MAILER_ADDRESS: 'MAILER_ADDRESS'
  MAILER_DOMAIN: 'MAILER_DOMAIN'
  MAILER_USER_NAME: 'DEVELOPMENT_MAILER_USER_NAME'
  MAILER_PASSWORD: 'DEVELOPMENT_MAILER_PASSWORD'
  MAILER_HOST: 'DEVELOPMENT_MAILER_HOST'

production:
  POSTGRES_USERNAME: 'deployer'
  POSTGRES_PASSWORD: 'deployer'
  HOST: 'HOST'
  FRONTEND: 'FRONTEND'
  MAILER_ADDRESS: 'MAILER_ADDRESS'
  MAILER_DOMAIN: 'MAILER_DOMAIN'
  MAILER_USER_NAME: 'DEVELOPMENT_MAILER_USER_NAME'
  MAILER_PASSWORD: 'DEVELOPMENT_MAILER_PASSWORD'
  MAILER_HOST: 'DEVELOPMENT_MAILER_HOST'
  UPSIDEAGENCY_DATABASE_PASSWORD: 'upsideagency'
